package com.framework.enums;

public enum ConfigProperties {
    BROWSER,
    OVERRIDEREPORTS,
    PASSEDTESTSSCREENSHOTS,
    FAILEDTESTSSCREENSHOTS,
    SKIPPEDTESTSCREENSHOTS,
    RETRYFAILEDTESTS,
    URL,
    RUNMODE;
}
